version: "3.0"
services:
  express:
    container_name: dragonball
    build: .
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - seed
    expose:
      - 3000
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
  seed:
    image: pkosiec/mongo-seeding
    environment:
      - DROP_DATABASE=true
      - REPLACE_ID=true
      - DB_HOST=db
      - DB_NAME=dragonball
      - DB_PORT=27017
    volumes:
      - ./data:/data
    working_dir: /data
    links: 
      - db
    depends_on:
      - db